views.view.group_invitations:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              options:
                submit_button: Filter
views.view.my_invitations:
  expected_config: {  }
  update_actions:
    change:
      display:
        default:
          display_options:
            exposed_form:
              options:
                submit_button: Filter
